services:
  - type: web
    name: lae-pro
    env: python
    buildCommand: |
      apt-get update && apt-get install -y build-essential wget unzip gcc make
      wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
      tar -xvzf ta-lib-0.4.0-src.tar.gz
      cd ta-lib && ./configure --prefix=/usr && make && make install
      pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
